import { readFileSync } from 'node:fs';

import { CONTAINER_HOME, CONTAINER_SCRIPT_DIR, CONTAINER_WORKSPACE } from '../../shared/presets.ts';
import type { AppConfig, Profile } from '../../shared/types.ts';
import { getActiveProfile, getConfig, getSecret, patchConfig } from '../config/store.ts';
import { execCapture, execChecked } from '../docker/container.ts';
import { readFileRaw, writeFileText } from '../docker/files.ts';
import { describeError, logInfo, logWarn } from '../logger.ts';
import { ensureImageSources } from '../docker/image.ts';
import { planExtensions } from './extensions.ts';
import { installSkills } from './skills.ts';
import { postCreatePath } from '../paths.ts';

const CLAUDE_JSON = `${CONTAINER_HOME}/.claude.json`;
const CLAUDE_DIR = `${CONTAINER_HOME}/.claude`;
const SETTINGS_JSON = `${CLAUDE_DIR}/settings.json`;
const TMUX_CONF = `${CONTAINER_HOME}/.tmux.conf`;

const ONBOARD_SCRIPT = `${CONTAINER_SCRIPT_DIR}/onboard.cjs`;
const LAUNCH_SCRIPT = `${CONTAINER_SCRIPT_DIR}/launch.sh`;
const POST_CREATE_SCRIPT = `${CONTAINER_SCRIPT_DIR}/post-create.sh`;

export function buildEnvBlock(profile: Profile, secret: string): Record<string, string> {
  const env: Record<string, string> = {};

  if (profile.baseUrl !== '') env['ANTHROPIC_BASE_URL'] = profile.baseUrl;

  if (secret !== '') {
    if (profile.authMode === 'authToken') {
      env['ANTHROPIC_AUTH_TOKEN'] = secret;
      env['ANTHROPIC_API_KEY'] = '';
    } else {
      env['ANTHROPIC_API_KEY'] = secret;
    }
  }

  if (profile.model !== '') env['ANTHROPIC_MODEL'] = profile.model;
  if (profile.sonnetModel !== '') env['ANTHROPIC_DEFAULT_SONNET_MODEL'] = profile.sonnetModel;
  if (profile.opusModel !== '') env['ANTHROPIC_DEFAULT_OPUS_MODEL'] = profile.opusModel;
  if (profile.haikuModel !== '') env['ANTHROPIC_DEFAULT_HAIKU_MODEL'] = profile.haikuModel;
  if (profile.fableModel !== '') env['ANTHROPIC_DEFAULT_FABLE_MODEL'] = profile.fableModel;

  if (profile.apiTimeoutMs !== null) env['API_TIMEOUT_MS'] = String(profile.apiTimeoutMs);

  if (profile.contextTokens !== null) env['CLAUDE_CODE_MAX_CONTEXT_TOKENS'] = String(profile.contextTokens);

  if (profile.disableTelemetry) env['DISABLE_TELEMETRY'] = '1';
  if (profile.disableNonEssentialTraffic) env['CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC'] = '1';

  env['DISABLE_AUTOUPDATER'] = '1';

  for (const [key, value] of Object.entries(profile.extraEnv)) {
    if (key.trim() === '') continue;
    env[key.trim()] = value;
  }

  return env;
}

function onboardingPatch(config: AppConfig, profile: Profile | null, secret: string): Record<string, unknown> {
  const patch: Record<string, unknown> = {
    hasCompletedOnboarding: true,
    bypassPermissionsModeAccepted: true,
    projects: {
      [CONTAINER_WORKSPACE]: {
        hasTrustDialogAccepted: true,
        hasCompletedProjectOnboarding: true,
      },
    },
  };

  if (config.autoApproveApiKey && profile?.authMode === 'apiKey' && secret !== '') {
    patch['customApiKeyResponses'] = { approved: [secret.slice(-20)], rejected: [] };
  }

  return patch;
}

function onboardScriptSource(patch: Record<string, unknown>, replaceKeys: readonly string[]): string {
  return `#!/usr/bin/env node
// Generated by cc-container-desktop. Merges the app-managed patch (onboarding
// flags when enabled, plus mcpServers) into ~/.claude.json.
// Regenerated on every provision; edits here are lost.
'use strict';
const fs = require('fs');
const os = require('os');
const path = require('path');

const target = path.join(process.env.HOME || os.homedir(), '.claude.json');
const patch = ${JSON.stringify(patch, null, 2)};
const replaceKeys = new Set(${JSON.stringify(replaceKeys)});

function isPlainObject(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function merge(base, extra, top) {
  const out = isPlainObject(base) ? { ...base } : {};
  for (const [key, value] of Object.entries(extra)) {
    if (top && replaceKeys.has(key)) out[key] = value;
    else out[key] = isPlainObject(value) ? merge(out[key], value, false) : value;
  }
  return out;
}

let current = {};
try {
  current = JSON.parse(fs.readFileSync(target, 'utf8'));
} catch {
  current = {};
}
if (!isPlainObject(current)) current = {};

const next = merge(current, patch, true);
const tmp = target + '.tmp';
fs.writeFileSync(tmp, JSON.stringify(next, null, 2) + '\\n', { mode: 0o600 });
fs.renameSync(tmp, target);
try { fs.chmodSync(target, 0o600); } catch {}
`;
}

function launchScriptSource(config: AppConfig): string {
  const flags = config.skipPermissions ? ' --dangerously-skip-permissions' : '';
  return `#!/usr/bin/env bash
# Generated by cc-container-desktop. Regenerated on every provision.
set -uo pipefail

node ${ONBOARD_SCRIPT} || echo "warn: onboarding patch failed" >&2

cd "${CONTAINER_WORKSPACE}" || exit 1
exec claude${flags} "$@"
`;
}

const TMUX_CONF_SOURCE = `# Generated by cc-container-desktop (only when no ~/.tmux.conf exists).
# Delete this file and re-provision to get it back.

# Claude Code asks for this one by name: without it the TUI cannot tell whether
# the terminal is focused, and prints a warning banner on every start.
set -g focus-events on

set -g mouse on
set -g history-limit 100000
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g base-index 1
set -g status-style "bg=colour236,fg=colour252"
set -g status-left "#[bold] cc #[default]"
set -g status-right "%Y-%m-%d %H:%M "
`;

async function fileExists(path: string): Promise<boolean> {
  const result = await execCapture(['test', '-e', path], { workdir: '/' });
  return result.exitCode === 0;
}

async function readJsonFromContainer(path: string): Promise<Record<string, unknown>> {
  if (!(await fileExists(path))) return {};
  try {
    const raw = await readFileRaw(path);
    if (raw.length === 0) return {};
    const parsed = JSON.parse(raw.toString('utf8')) as unknown;
    if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
      await keepAside(path);
      return {};
    }
    return parsed as Record<string, unknown>;
  } catch (error) {
    await keepAside(path);
    logWarn(
      'provision',
      `${path} を読めなかったので作り直します / rewriting unreadable ${path}: ${describeError(error)}`,
    );
    return {};
  }
}

async function keepAside(path: string): Promise<void> {
  const backup = `${path}.broken-${Date.now().toString(36)}`;
  const result = await execCapture(['cp', '-p', path, backup], { workdir: '/' });
  if (result.exitCode === 0) {
    logWarn('provision', `退避しました / kept a copy of the unreadable file at ${backup}`);
  }
}

export async function provisionContainer(): Promise<string> {
  const config = getConfig();
  const profile = getActiveProfile();
  const secret = profile === null ? '' : getSecret(profile.id);

  await execChecked(['mkdir', '-p', CLAUDE_DIR, CONTAINER_WORKSPACE], { workdir: '/' });
  await execChecked(['mkdir', '-p', CONTAINER_SCRIPT_DIR], { workdir: '/', asRoot: true });

  const existingClaudeJson = await readJsonFromContainer(CLAUDE_JSON);
  const existingSettings = await readJsonFromContainer(SETTINGS_JSON);
  const plan = planExtensions(config.extensions, config.managed, existingClaudeJson, existingSettings);
  for (const warning of plan.warnings) logWarn('provision', warning);

  const patch = config.autoOnboarding
    ? { ...onboardingPatch(config, profile, secret), ...plan.claudeJson }
    : { ...plan.claudeJson };
  const replaceKeys = Object.keys(plan.claudeJson);
  await writeFileText(ONBOARD_SCRIPT, onboardScriptSource(patch, replaceKeys), 0o700);
  await writeFileText(LAUNCH_SCRIPT, launchScriptSource(config), 0o755);
  await execChecked(['node', ONBOARD_SCRIPT], { workdir: CONTAINER_HOME });

  const settings: Record<string, unknown> = { ...existingSettings, ...plan.settings };
  if (profile === null) {
    delete settings['env'];
  } else {
    settings['env'] = buildEnvBlock(profile, secret);
  }
  if (config.autoOnboarding) {
    settings['skipDangerousModePermissionPrompt'] = true;
  }
  await writeFileText(SETTINGS_JSON, `${JSON.stringify(settings, null, 2)}\n`, 0o600);

  patchConfig({ managed: plan.managed });

  if (!(await fileExists(TMUX_CONF))) {
    await writeFileText(TMUX_CONF, TMUX_CONF_SOURCE, 0o644);
  }

  ensureImageSources();
  const postCreate = readFileSync(postCreatePath(), 'utf8').replaceAll('\r\n', '\n');
  await writeFileText(POST_CREATE_SCRIPT, postCreate, 0o755);
  const postResult = await execCapture(['bash', POST_CREATE_SCRIPT], { workdir: CONTAINER_WORKSPACE });
  for (const line of `${postResult.stdout}${postResult.stderr}`.split('\n')) {
    if (line.trim() !== '') logInfo('provision', line.trim());
  }
  if (postResult.exitCode !== 0) {
    logWarn(
      'provision',
      `post-create が exit ${postResult.exitCode} で終了しました / post-create exited ${postResult.exitCode}`,
    );
  }

  const skills = await installSkills(config.extensions.skillInstalls);
  for (const warning of skills.warnings) logWarn('provision', warning);

  const extras: string[] = [];
  if (plan.managed.mcpServers.length > 0) extras.push(`MCP ${plan.managed.mcpServers.length}`);
  if (plan.managed.plugins.length > 0) extras.push(`plugins ${plan.managed.plugins.length}`);
  if (skills.installed > 0) extras.push(`skills ${skills.installed}`);

  const summary =
    (profile === null
      ? 'プロファイル未選択のまま設定を書き込みました / provisioned without a profile'
      : `${profile.name} → ${profile.baseUrl || '(base URL 未設定)'} / ${profile.model || '(model 未設定)'}` +
        `${secret === '' ? ' — API キー未設定 / no API key' : ''}`) +
    (extras.length === 0 ? '' : ` — ${extras.join(', ')}`);
  logInfo('provision', `設定を書き込みました / provisioned: ${summary}`);
  return summary;
}

export function claudeLaunchCommand(): string {
  return `${LAUNCH_SCRIPT}; exec bash -l`;
}
