/**
 * Pushing the active profile into the container.
 *
 * Three files matter:
 *
 *  - `~/.claude.json` — carries `hasCompletedOnboarding`. Merged, never replaced,
 *    so session history and per-project state survive.
 *  - `~/.claude/settings.json` — carries the `env` block that points Claude Code
 *    at the endpoint. Only `env` is replaced; anything else you add by hand
 *    (hooks, permissions, statusLine) is preserved.
 *  - `/opt/cc/onboard.cjs` + `/opt/cc/launch.sh` — regenerated each time, so the
 *    onboarding flags get re-asserted at the moment Claude Code actually starts,
 *    not just when the app last provisioned.
 */

import { readFileSync } from 'node:fs';

import { CONTAINER_HOME, CONTAINER_SCRIPT_DIR, CONTAINER_WORKSPACE } from '../../shared/presets.ts';
import type { AppConfig, Profile } from '../../shared/types.ts';
import { getActiveProfile, getConfig, getSecret } from '../config/store.ts';
import { execCapture, execChecked } from '../docker/container.ts';
import { readFileRaw, writeFileText } from '../docker/files.ts';
import { describeError, logInfo, logWarn } from '../logger.ts';
import { ensureImageSources } from '../docker/image.ts';
import { postCreatePath } from '../paths.ts';

const CLAUDE_DIR = `${CONTAINER_HOME}/.claude`;
const SETTINGS_JSON = `${CLAUDE_DIR}/settings.json`;
const TMUX_CONF = `${CONTAINER_HOME}/.tmux.conf`;

const ONBOARD_SCRIPT = `${CONTAINER_SCRIPT_DIR}/onboard.cjs`;
const LAUNCH_SCRIPT = `${CONTAINER_SCRIPT_DIR}/launch.sh`;
const POST_CREATE_SCRIPT = `${CONTAINER_SCRIPT_DIR}/post-create.sh`;

/**
 * Builds the `env` block Claude Code reads at startup.
 *
 * Only non-empty values are emitted: an empty string means "unset" to Claude
 * Code's provider selection, and writing one would actively cancel a value the
 * user exported in the container's shell.
 */
export function buildEnvBlock(profile: Profile, secret: string): Record<string, string> {
  const env: Record<string, string> = {};

  if (profile.baseUrl !== '') env['ANTHROPIC_BASE_URL'] = profile.baseUrl;

  if (secret !== '') {
    // Exactly one of these: leaving the other set would make Claude Code send
    // both headers, and gateways differ on which one wins.
    if (profile.authMode === 'authToken') env['ANTHROPIC_AUTH_TOKEN'] = secret;
    else env['ANTHROPIC_API_KEY'] = secret;
  }

  if (profile.model !== '') env['ANTHROPIC_MODEL'] = profile.model;
  if (profile.sonnetModel !== '') env['ANTHROPIC_DEFAULT_SONNET_MODEL'] = profile.sonnetModel;
  if (profile.opusModel !== '') env['ANTHROPIC_DEFAULT_OPUS_MODEL'] = profile.opusModel;
  if (profile.haikuModel !== '') env['ANTHROPIC_DEFAULT_HAIKU_MODEL'] = profile.haikuModel;

  if (profile.apiTimeoutMs !== null) env['API_TIMEOUT_MS'] = String(profile.apiTimeoutMs);

  // Claude Code assumes a 200k window for a model ID it does not recognize, and
  // proactively compacts against that. Declaring the real window keeps a
  // large-context third-party model from being compacted away at 200k.
  if (profile.contextTokens !== null) env['CLAUDE_CODE_MAX_CONTEXT_TOKENS'] = String(profile.contextTokens);

  if (profile.disableTelemetry) env['DISABLE_TELEMETRY'] = '1';
  if (profile.disableNonEssentialTraffic) env['CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC'] = '1';

  // The image owns the Claude Code version; an in-place update would only land
  // in the container's throwaway layer and vanish on the next rebuild.
  env['DISABLE_AUTOUPDATER'] = '1';

  // User-supplied entries go last so they can override anything above.
  for (const [key, value] of Object.entries(profile.extraEnv)) {
    if (key.trim() === '') continue;
    env[key.trim()] = value;
  }

  return env;
}

/** The patch merged into `~/.claude.json` on every launch. */
function onboardingPatch(config: AppConfig, profile: Profile | null, secret: string): Record<string, unknown> {
  const patch: Record<string, unknown> = {
    hasCompletedOnboarding: true,
    bypassPermissionsModeAccepted: true,
    projects: {
      [CONTAINER_WORKSPACE]: {
        hasTrustDialogAccepted: true,
        hasCompletedProjectOnboarding: true,
      },
    },
  };

  // Claude Code asks for one-time approval before an ANTHROPIC_API_KEY overrides
  // a subscription. It records the decision against a truncated form of the key,
  // so both forms go in — a wrong guess is inert, a missing one costs a prompt.
  if (config.autoApproveApiKey && profile?.authMode === 'apiKey' && secret !== '') {
    patch['customApiKeyResponses'] = { approved: [secret.slice(-20), secret], rejected: [] };
  }

  return patch;
}

/** A CommonJS one-file merger, run inside the container as the `claude` user. */
function onboardScriptSource(patch: Record<string, unknown>): string {
  return `#!/usr/bin/env node
// Generated by cc-container-desktop. Re-asserts Claude Code's onboarding flags.
// Regenerated on every provision; edits here are lost.
'use strict';
const fs = require('fs');
const os = require('os');
const path = require('path');

const target = path.join(process.env.HOME || os.homedir(), '.claude.json');
const patch = ${JSON.stringify(patch, null, 2)};

function isPlainObject(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function merge(base, extra) {
  const out = isPlainObject(base) ? { ...base } : {};
  for (const [key, value] of Object.entries(extra)) {
    out[key] = isPlainObject(value) ? merge(out[key], value) : value;
  }
  return out;
}

let current = {};
try {
  current = JSON.parse(fs.readFileSync(target, 'utf8'));
} catch {
  current = {};
}
if (!isPlainObject(current)) current = {};

const next = merge(current, patch);
const tmp = target + '.tmp';
fs.writeFileSync(tmp, JSON.stringify(next, null, 2) + '\\n');
fs.renameSync(tmp, target);
`;
}

/** The wrapper tmux runs. Re-onboards, then hands the terminal to Claude Code. */
function launchScriptSource(config: AppConfig): string {
  const flags = config.skipPermissions ? ' --dangerously-skip-permissions' : '';
  return `#!/usr/bin/env bash
# Generated by cc-container-desktop. Regenerated on every provision.
set -uo pipefail

node ${ONBOARD_SCRIPT} || echo "warn: onboarding patch failed" >&2

cd "${CONTAINER_WORKSPACE}" || exit 1
exec claude${flags} "$@"
`;
}

const TMUX_CONF_SOURCE = `# Generated by cc-container-desktop (only when no ~/.tmux.conf exists).
# Delete this file and re-provision to get it back.

# Claude Code asks for this one by name: without it the TUI cannot tell whether
# the terminal is focused, and prints a warning banner on every start.
set -g focus-events on

set -g mouse on
set -g history-limit 100000
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g base-index 1
set -g status-style "bg=colour236,fg=colour252"
set -g status-left "#[bold] cc #[default]"
set -g status-right "%Y-%m-%d %H:%M "
`;

async function fileExists(path: string): Promise<boolean> {
  const result = await execCapture(['test', '-e', path], { workdir: '/' });
  return result.exitCode === 0;
}

/** Reads a JSON file from the container, tolerating absence and corruption. */
async function readJsonFromContainer(path: string): Promise<Record<string, unknown>> {
  if (!(await fileExists(path))) return {};
  try {
    const raw = await readFileRaw(path);
    if (raw.length === 0) return {};
    const parsed = JSON.parse(raw.toString('utf8')) as unknown;
    if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) return {};
    return parsed as Record<string, unknown>;
  } catch (error) {
    logWarn(
      'provision',
      `${path} を読めなかったので作り直します / rewriting unreadable ${path}: ${describeError(error)}`,
    );
    return {};
  }
}

/**
 * Writes the profile into the container and returns a human-readable summary.
 *
 * Safe to call repeatedly; every step is idempotent.
 */
export async function provisionContainer(): Promise<string> {
  const config = getConfig();
  const profile = getActiveProfile();
  const secret = profile === null ? '' : getSecret(profile.id);

  await execChecked(['mkdir', '-p', CLAUDE_DIR, CONTAINER_WORKSPACE], { workdir: '/' });
  await execChecked(['mkdir', '-p', CONTAINER_SCRIPT_DIR], { workdir: '/', asRoot: true });

  // 1. Onboarding flags. The generated script is the single implementation, so
  //    the app and the launch wrapper cannot drift apart.
  const patch = onboardingPatch(config, profile, secret);
  await writeFileText(ONBOARD_SCRIPT, onboardScriptSource(patch), 0o755);
  await writeFileText(LAUNCH_SCRIPT, launchScriptSource(config), 0o755);
  if (config.autoOnboarding) {
    await execChecked(['node', ONBOARD_SCRIPT], { workdir: CONTAINER_HOME });
  }

  // 2. settings.json — replace `env`, keep every other key the user added.
  const existing = await readJsonFromContainer(SETTINGS_JSON);
  const settings: Record<string, unknown> = { ...existing };
  if (profile === null) {
    delete settings['env'];
  } else {
    settings['env'] = buildEnvBlock(profile, secret);
  }
  await writeFileText(SETTINGS_JSON, `${JSON.stringify(settings, null, 2)}\n`, 0o600);

  // 3. tmux defaults, only when the user has not written their own.
  if (!(await fileExists(TMUX_CONF))) {
    await writeFileText(TMUX_CONF, TMUX_CONF_SOURCE, 0o644);
  }

  // 4. The editable post-create hook, pushed in fresh and run.
  ensureImageSources();
  const postCreate = readFileSync(postCreatePath(), 'utf8').replaceAll('\r\n', '\n');
  await writeFileText(POST_CREATE_SCRIPT, postCreate, 0o755);
  const postResult = await execCapture(['bash', POST_CREATE_SCRIPT], { workdir: CONTAINER_WORKSPACE });
  for (const line of `${postResult.stdout}${postResult.stderr}`.split('\n')) {
    if (line.trim() !== '') logInfo('provision', line.trim());
  }
  if (postResult.exitCode !== 0) {
    logWarn(
      'provision',
      `post-create が exit ${postResult.exitCode} で終了しました / post-create exited ${postResult.exitCode}`,
    );
  }

  const summary =
    profile === null
      ? 'プロファイル未選択のまま設定を書き込みました / provisioned without a profile'
      : `${profile.name} → ${profile.baseUrl || '(base URL 未設定)'} / ${profile.model || '(model 未設定)'}` +
        `${secret === '' ? ' — API キー未設定 / no API key' : ''}`;
  logInfo('provision', `設定を書き込みました / provisioned: ${summary}`);
  return summary;
}

/** The command tmux should run for a Claude Code session. */
export function claudeLaunchCommand(): string {
  // Falling back to a login shell keeps the tmux session alive after Claude Code
  // exits, so "reattach" lands somewhere useful instead of a dead session.
  return `${LAUNCH_SCRIPT}; exec bash -l`;
}
